from matlas.core.shared_category import SharedCategory

# Hand-maintained, covers only the MCCs present in the Week-1 gazetteer seed
# (data/regions/us/gazetteer.us.jsonl). Grow alongside the gazetteer, not ahead of it.
MCC_TO_SHARED_CATEGORY: dict[str, SharedCategory] = {
    "5814": SharedCategory.FOOD_AND_DRINK,
    "5411": SharedCategory.FOOD_AND_DRINK,
    "3058": SharedCategory.TRAVEL,
    "3000": SharedCategory.TRAVEL,
    "3509": SharedCategory.TRAVEL,
    "3504": SharedCategory.TRAVEL,
    "4121": SharedCategory.TRANSPORTATION,
    "5815": SharedCategory.ENTERTAINMENT,
    "5399": SharedCategory.GENERAL_MERCHANDISE,
    "5310": SharedCategory.GENERAL_MERCHANDISE,
    "5912": SharedCategory.MEDICAL,
    "4814": SharedCategory.RENT_AND_UTILITIES,
    "4899": SharedCategory.RENT_AND_UTILITIES,
    "5211": SharedCategory.HOME_IMPROVEMENT,
    "7230": SharedCategory.PERSONAL_CARE,
    "8398": SharedCategory.GOVERNMENT_AND_NON_PROFIT,
    "7276": SharedCategory.GENERAL_SERVICES,
    "7832": SharedCategory.ENTERTAINMENT,
    "5300": SharedCategory.GENERAL_MERCHANDISE,
    "5311": SharedCategory.GENERAL_MERCHANDISE,
    "5541": SharedCategory.TRANSPORTATION,
    "5732": SharedCategory.GENERAL_MERCHANDISE,
    "5812": SharedCategory.FOOD_AND_DRINK,
    "7512": SharedCategory.TRAVEL,
    "5651": SharedCategory.GENERAL_MERCHANDISE,
    "5661": SharedCategory.GENERAL_MERCHANDISE,
    "5941": SharedCategory.GENERAL_MERCHANDISE,
    "5945": SharedCategory.GENERAL_MERCHANDISE,
    "5942": SharedCategory.GENERAL_MERCHANDISE,
    "5992": SharedCategory.GENERAL_MERCHANDISE,
    "5499": SharedCategory.FOOD_AND_DRINK,
    "7997": SharedCategory.PERSONAL_CARE,
    "5995": SharedCategory.GENERAL_MERCHANDISE,
    "5943": SharedCategory.GENERAL_MERCHANDISE,
    "5712": SharedCategory.GENERAL_MERCHANDISE,
    "5533": SharedCategory.TRANSPORTATION,
    "7542": SharedCategory.TRANSPORTATION,
    "7523": SharedCategory.TRANSPORTATION,
    "4215": SharedCategory.GENERAL_SERVICES,
    "6300": SharedCategory.GENERAL_SERVICES,
    "4900": SharedCategory.RENT_AND_UTILITIES,
    "7011": SharedCategory.TRAVEL,
    "4511": SharedCategory.TRAVEL,
    "6011": SharedCategory.BANK_FEES,
    "5921": SharedCategory.GENERAL_MERCHANDISE,
    "7538": SharedCategory.TRANSPORTATION,
    "5511": SharedCategory.TRANSPORTATION,
    "7211": SharedCategory.GENERAL_SERVICES,
    "4214": SharedCategory.GENERAL_SERVICES,
    "0742": SharedCategory.GENERAL_SERVICES,
}
